[package]
name = "SagePost"
edition = "2024.beta"
version = "0.0.1"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

SageAdmin = { local = "../admin" }
SageChannel = { local = "../channel" }
SageImmutable = { local = "../immutable" }

[addresses]
sage = "0x0"
